src/djeocad/urls.py
from django.urls import path

from .views import (
    DrawingDetailView,
    DrawingListView,
    EntityDataListView,
    add_block_insertion,
    change_block_insertion,
    create_entity_data,
    csv_download,
    delete_block_insertion,
    delete_entity_data,
    drawing_download,
)

app_name = "djeocad"
urlpatterns = [
    path("", DrawingListView.as_view(), name="drawing_list"),
    path("<pk>", DrawingDetailView.as_view(), name="drawing_detail"),
    path("<pk>/insertion", add_block_insertion, name="insertion_create"),
    path("insertion/<pk>/change", change_block_insertion, name="insertion_change"),
    path("insertion/<pk>/delete", delete_block_insertion, name="insertion_delete"),
    path("insertion/<pk>/data-list", EntityDataListView.as_view(), name="data_list"),
    path("insertion/<pk>/data-create", create_entity_data, name="data_create"),
    path("entity-data/<pk>/delete", delete_entity_data, name="data_delete"),
    path(
        "<pk>/csv",
        csv_download,
        name="drawing_csv",
    ),
    path(
        "<pk>/download",
        drawing_download,
        name="drawing_download",
    ),
]

src/djeocad/templates/djeocad/drawing_detail.html
{% extends "base.html" %}
{% load leaflet_tags %}

{% block extra-head %}
  {% leaflet_js %}
  {% leaflet_css %}
  <style>
    .leaflet-container {  /* all maps */
      height: 600px;
    }
  </style>
{% endblock extra-head %}

{% block content %}
  {% include "djeocad/htmx/drawing_detail.html" %}
{% endblock content %}

src/djeocad/templates/djeocad/drawing_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load leaflet_tags %}
{% load geojson_tags %}

{% block extra-head %}
  {% leaflet_js %}
  {% leaflet_css %}
  <style>
    .leaflet-container {  /* all maps */
      height: 600px;
    }
  </style>
{% endblock extra-head %}

{% block content %}
  <details>
    <summary style="font-size: 1.875em;">{% trans "All drawings" %}</summary>
    <ul>
      <li>
        <a href="/admin/djeocad/drawing/add/">
          {% trans "Add drawing" %}
        </a>
      </li>
      {% if unreferenced %}
        {% for unref in unreferenced %}
          <li>
            <a href="/admin/djeocad/drawing/{{ unref.id }}/change/">
              {% trans "Unreferenced drawing" %}: {{ unref.title }}
            </a>
          </li>
        {% endfor %}
      {% endif %}
    </ul>
  </details>
  <script id="marker_data" type="application/json">{{ object_list|geojsonfeature:"popupContent"|safe }}</script>
  {% include "djeocad/map_data.html" %}
  <script src="{% static 'djeocad/js/map_script.js'%}"></script>
  <div>
    {% leaflet_map "mymap" callback="window.map_init" %}
  </div>
{% endblock content %}

src/djeocad/templates/djeocad/entity_change.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load leaflet_tags %}
{% load geojson_tags %}

{% block extra-head %}
  {% leaflet_js %}
  {% leaflet_css %}
  <style>
    .leaflet-container {  /* all maps */
      height: 600px;
    }
  </style>
{% endblock extra-head %}

{% block content %}
  <h2>{% trans "Change insertion of drawing" %}: {{ drawing.title }}</h2>
  <form action="{% url 'djeocad:insertion_change' pk=object.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <p>{% trans "Click on the map below to change coordinates" %}</p>
    <input type="submit" value="Submit">
  </form>
  <ul>
    <li><a href="{% url 'djeocad:drawing_detail' pk=drawing.id %}">
      {% trans "Back to drawing" %}: {{ drawing.title }}
    </a></li>
    <li><a style="color: red;"
           href="{% url 'djeocad:insertion_delete' pk=object.id %}">
      {% trans "Delete insertion" %}
    </a></li>
  </ul>
  <div id="entity-data" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% include "djeocad/htmx/entity_data_list.html" %}
  </div>
  <script id="marker_data" type="application/json">{{ object|geojsonfeature:":insertion"|safe }}</script>
  {% include "djeocad/map_data.html" %}
  <script id="line_data" type="application/json">{{ lines|geojsonfeature|safe }}</script>
  {{ layer_list|json_script:"layer_data" }}
  <script src="{% static 'djeocad/js/change_script.js'%}"></script>
  <div>
    {% leaflet_map "mymap" callback="window.map_init" %}
  </div>
  <script src="{% static "djeocad/js/htmx.min.js" %}"></script>
{% endblock content %}

src/djeocad/templates/djeocad/entity_create.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load leaflet_tags %}
{% load geojson_tags %}

{% block extra-head %}
  {% leaflet_js %}
  {% leaflet_css %}
  <style>
    .leaflet-container {  /* all maps */
      height: 600px;
    }
  </style>
{% endblock extra-head %}

{% block content %}
  <h2>{% trans "Add insertion to drawing" %}: {{ drawing.title }}</h2>
  <form action="{% url 'djeocad:insertion_create' pk=drawing.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <p>{% trans "Click on the map below to change coordinates" %}</p>
    <input type="submit" value="Submit">
  </form>
  <script id="marker_data" type="application/json">{{ drawing|geojsonfeature|safe }}</script>
  {% include "djeocad/map_data.html" %}
  <script id="line_data" type="application/json">{{ lines|geojsonfeature|safe }}</script>
  {{ layer_list|json_script:"layer_data" }}
  <script src="{% static 'djeocad/js/change_script.js'%}"></script>
  <div>
    {% leaflet_map "mymap" callback="window.map_init" %}
  </div>
{% endblock content %}